#pragma once

// Umbrella header — pulls in the entire METL public API.
// Every standalone-compilable header in <metl/> is included here, so
// `#include <metl/metl.hpp>` is equivalent to including the whole library.

#include "metl/arena_allocator.hpp"
#include "metl/assert.hpp"
#include "metl/atomic_ref.hpp"
#include "metl/attributes.hpp"
#include "metl/bit.hpp"
#include "metl/bitfield.hpp"
#include "metl/compiler.hpp"
#include "metl/config.hpp"
#include "metl/crc16.hpp"
#include "metl/crc32.hpp"
#include "metl/crc8.hpp"
#include "metl/delegate.hpp"
#include "metl/detail/construct.hpp"
#include "metl/endian.hpp"
#include "metl/event_dispatcher.hpp"
#include "metl/expected.hpp"
#include "metl/fixed_deque.hpp"
#include "metl/fixed_function.hpp"
#include "metl/fixed_queue.hpp"
#include "metl/fixed_stack.hpp"
#include "metl/fixed_string.hpp"
#include "metl/fixed_vector.hpp"
#include "metl/flat_map.hpp"
#include "metl/flat_set.hpp"
#include "metl/fsm.hpp"
#include "metl/function_ref.hpp"
#include "metl/hash.hpp"
#include "metl/in_place.hpp"
#include "metl/intrusive_ptr.hpp"
#include "metl/lookup_table.hpp"
#include "metl/mmio.hpp"
#include "metl/monotonic_buffer.hpp"
#include "metl/object_pool.hpp"
#include "metl/optimization.hpp"
#include "metl/optional.hpp"
#include "metl/register_access.hpp"
#include "metl/ring_buffer.hpp"
#include "metl/scope_exit.hpp"
#include "metl/span.hpp"
#include "metl/spsc_queue.hpp"
#include "metl/static_allocator.hpp"
#include "metl/static_message_queue.hpp"
#include "metl/static_unordered_map.hpp"
#include "metl/static_unordered_set.hpp"
#include "metl/type_traits.hpp"
#include "metl/variant.hpp"
#include "metl/version.hpp"

// Cooperative coroutine-style tasks (C++17 macro/state-machine based; no
// <coroutine> support or extra compiler flags required).
#include "metl/coro/protothread.hpp"
#include "metl/coro/scheduler.hpp"
#include "metl/coro/stepper.hpp"
